const WHATSAPP_NUMBER = "5491164137699";
const MERCADO_LIBRE_BASE = "https://listado.mercadolibre.com.ar/";

// Para editar la lista:
// - estado: "Disponible", "Reservado" o "Comprado"
// - prioridad: "Alta", "Media" o "Baja"
// - linkCompra: podés reemplazarlo por una URL específica de Mercado Libre o tienda.
// - imagen: podés usar una URL externa o una ruta local dentro de assets/img/productos/.
window.GIFTS = [
  {"id":"cocina","nombre":"Cocina de juguete de madera","estado":"Disponible","categoria":"Juego simbólico","prioridad":"Alta","precio":"$$$","edad":"2-5 años","icono":"🍳","descripcion":"Cocina infantil de madera para juego simbólico, ideal para estimular la imaginación, la autonomía y el juego de roles. Un juguete que puede acompañarla durante varios años.","caracteristicas":["Preferentemente de madera","Apta desde 2 años","Estructura firme y estable","Altura infantil","Con horno, hornallas y bacha","Accesorios grandes y seguros","Sin piezas pequeñas peligrosas","Colores suaves o neutros"],"busqueda":"cocina de juguete de madera infantil","linkCompra":"https://meli.la/2uEV322","imagen":"assets/img/productos/cocina.png"},
  {"id": "babiators", "nombre": "Lentes de sol Babiators",   "estado": "Disponible",   "categoria": "Playa y verano",   "prioridad": "Alta",  "precio": "$$$", "edad": "3-5 años","icono": "🕶️",  "descripcion": "Lentes de sol infantiles Babiators en color Sweet Cream, ideales para playa, pileta y días de mucho sol.","caracteristicas": [    "Marca preferida: Babiators",    "Color: Sweet Cream",    "Talle recomendado: 3-5Y",    "Protección UV400",    "100% protección UVA/UVB",    "Montura flexible",    "Lentes resistentes a impacto"  ],  "busqueda": "Babiators Sweet Cream 3-5Y",  "linkCompra": "https://tiendamia.com.uy/p/amz/b0dtrfc1ql",  "imagen": "assets/img/productos/lentes.jpg"},
  {"id":"calzado-playa","nombre":"Calzado para playa","estado":"Reservado","categoria":"Playa y verano","prioridad":"Alta","precio":"$$","edad":"2-3 años","icono":"🩴","descripcion":"Sandalias para playa (Consultar talle y modelo antes de comprar).","caracteristicas":["Suela antideslizante","Apto agua","Que no se salga fácil","Liviano","Talle a confirmar"],"busqueda":"Sandalias playa niña 2 años","linkCompra":"https://meli.la/2VG1S4E","imagen":"assets/img/productos/sandalias.png"},
  {"id":"memotest","nombre":"Memotest infantil con animales","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Media","precio":"$","edad":"2-4 años","icono":"🐾","descripcion":"Juego de memoria con imágenes simples para vocabulario y concentración.","caracteristicas":["Imágenes de animales","Tarjetas Grandes","Tarjetas resistentes","Pocas parejas para empezar","Apto 2-4 años","Ilustraciones claras"],"busqueda":"memotest animales infantil","linkCompra":"https://www.tentamarket.com.ar/productos/memo-test-animales-gigante-didactico/","imagen":"assets/img/productos/memotest.png"},
  {"id":"pizarra","nombre":"Pizarra magnética y Pizarrón Doble","estado":"Disponible","categoria":"Arte y creatividad","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"✏️","descripcion":"Pizarra para dibujar, pegar imanes y practicar trazos.","caracteristicas":["Magnética","Doble: Pizarrón + Magnético","Lavable","Estable","Apta niños","Mejor si incluye marcadores/imanes grandes"],"busqueda":"pizarra magnética infantil","linkCompra":"https://meli.la/1qzbLXt","imagen":"assets/img/productos/pizarra.png"},
  {"id":"uniforme-pantalon","nombre":"Pantalón del uniforme del jardín","estado":"Disponible","categoria":"Ropa y jardín","prioridad":"Alta","precio":"$$","edad":"2-3 años","icono":"👖","descripcion":"Pantalón del uniforme del jardín San Pedro TALLE 1.","caracteristicas":["Talle: 1","Se vende en Carrousel","Álvarez Jonte 4724, C1407"],"busqueda":"pantalón uniforme jardín niña","linkCompra":"https://www.instagram.com/p/DUS-ZUcDoHD/?igsh=c2NpeHhkeXV6Mmo5","imagen":"assets/img/productos/pantalon_san_pedro.jpg"},
  {"id":"domino-animales","nombre":"Dominó de animales","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Baja","precio":"$","edad":"2-4 años","icono":"🦁","descripcion":"Dominó simple con ilustraciones de animales.","caracteristicas":["Ilustraciones grandes","Piezas resistentes","Animales reconocibles","Reglas simples","Apto 2-4 años"],"busqueda":"dominó animales infantil","linkCompra":"https://www.djurkids.com.ar/productos/domino-animal/?srsltid=AfmBOoreEEGfTKDimaqtFDAq5zn6y8A1SHEFoqXE65xoQOPG4Ppe4vAy","imagen":"assets/img/productos/domino.png"},
  {"id":"rompecabezas 4-8 piezas","nombre":"Rompecabezas para 2 años","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Media","precio":"$","edad":"2-4 años","icono":"🧩","descripcion":"Rompecabezas progresivo con piezas grandes para atención y motricidad fina.","caracteristicas":["4-8 piezas","Piezas grandes y resistentes","Imágenes simples y atractivas","Apto edad 2-4 años","Mejor si es progresivo y magnético"],"busqueda":"rompecabezas 2-4 piezas infantil 3 años","linkCompra":"https://meli.la/21PaH4w","imagen":"assets/img/productos/rompe.png"},
  {"id":"biblioteca-frontal","nombre":"Biblioteca frontal Montessori","estado":"Disponible","categoria":"Muebles infantiles","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"📖","descripcion":"Biblioteca baja con libros a la vista para favorecer autonomía.","caracteristicas":["Frontal, libros visibles","Altura baja","Estructura estable","Sin puntas filosas","Madera o material resistente"],"busqueda":"biblioteca frontal montessori infantil","linkCompra":"https://meli.la/1c9pp4L","imagen":"assets/img/productos/biblioteca.png"},
  {"id":"duplo","nombre":"LEGO DUPLO o compatibles","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Media","precio":"$$$","edad":"2+ años","icono":"🧱","descripcion":"Caja de bloques grandes LEGO DUPLO para construcción libre, juego creativo y motricidad fina. Ideal como primer set para usar durante varios años.","caracteristicas":["LEGO DUPLO original o compatible","Piezas grandes y seguras","Apto desde 2 años","Preferentemente caja con bloques variados","Incluye piezas para construir libremente","Compatible con futuros sets DUPLO"],"busqueda":"LEGO DUPLO Classic Deluxe Brick Box","linkCompra":"https://meli.la/2ibF5Cr","imagen":"assets/img/productos/duplo.png"},
  {"id":"set-cubiertos","nombre":"Set de cubiertos infantiles","estado":"Disponible","categoria":"Jardín y uso diario","prioridad":"Media","precio":"$","edad":"2+ años","icono":"🍴","descripcion":"Set de cubiertos infantiles para acompañar la autonomía en las comidas, con tamaño y agarre adecuados para niños pequeños.","caracteristicas":["Incluye cuchara, tenedor y cuchillo infantil","Tamaño adecuado para niños","Mango cómodo y seguro","Material resistente","Apto para uso diario","Ideal para jardín o casa"],"busqueda":"set cubiertos infantiles","linkCompra":"https://meli.la/1CNv12u","imagen":"assets/img/productos/cubiertos.png"},
  {"id":"malla-uv","nombre":"Malla enteriza con protección UV","estado":"Comprado","categoria":"Playa y verano","prioridad":"Alta","precio":"$$","edad":"2-3 años","icono":"🩱","descripcion":"Malla o traje de baño enterizo para pileta y vacaciones en la playa.","caracteristicas":["Tela con protección UV preferentemente UPF 50+","Enteriza o con buena cobertura","Cómoda para moverse","Secado rápido","Talle 2-3 años a confirmar"],"busqueda":"malla enteriza protección UV niña 2 años","linkCompra":"","imagen":"assets/img/productos/malla.png"},
  {"id":"poncho-playa-uv","nombre":"Poncho de salida de playa UV","estado":"Comprado","categoria":"Playa y verano","prioridad":"Alta","precio":"$$","edad":"2-4 años","icono":"🏖️","descripcion":"Poncho/toallón para salida de mar o pileta.","caracteristicas":["Preferentemente con protección UV o tela de secado rápido","Con capucha","Tamaño infantil","Tela suave","Fácil de lavar"],"busqueda":"poncho salida de playa uv niña 2 años","linkCompra":"","imagen":"assets/img/productos/poncho.png"},
  {"id":"mesa-silla","nombre":"Juego de mesa y sillas infantil","estado":"Comprado","categoria":"Muebles infantiles","prioridad":"Media","precio":"$$$","edad":"2-6 años","icono":"🪑","descripcion":"Set bajo para dibujar, leer, comer o jugar.","caracteristicas":["Mesa baja + silla/s","Esquinas redondeadas","Fácil limpieza","Estructura estable","Tamaño infantil"],"busqueda":"mesa silla infantil madera","linkCompra":"","imagen":"assets/img/productos/mesa.png"},
  {"id":"toy-story-buddy","nombre":"Muñeco Toy Story Woody","estado":"Comprado","categoria":"Personajes y muñecos","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"🤠","descripcion":"Muñeco de personaje Toy Story para juego simbólico.","caracteristicas":["Personaje: Woody según disponibilidad","Tamaño infantil","Material resistente","Sin piezas pequeñas peligrosas","Apto para 2+ años"],"busqueda":"muñeco toy story buddy woody","linkCompra":"","imagen":"assets/img/productos/woody.png"},
  {"id":"toy-story-jessie","nombre":"Muñeco Toy Story Jessie","estado":"Comprado","categoria":"Personajes y muñecos","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"👢","descripcion":"Muñeca Jessie de Toy Story para juego simbólico.","caracteristicas":["Personaje: Jessie","Tamaño infantil","Material resistente","Sin piezas pequeñas peligrosas","Apto para 2+ años"],"busqueda":"muñeco toy story jessie","linkCompra":"","imagen":"assets/img/productos/jessie.png"},
  {"id":"remera-blanca-ml","nombre":"Remera manga larga blanca","estado":"Comprado","categoria":"Ropa y jardín","prioridad":"Alta","precio":"$","edad":"2-3 años","icono":"👕","descripcion":"Remera blanca manga larga para jardín y uso diario.","caracteristicas":["Manga larga","Color blanco liso","Algodón o tela suave","Cuello cómodo","Talle a confirmar"],"busqueda":"remera manga larga blanca niña 2 años","linkCompra":"","imagen":"assets/img/productos/remera.png"},
  {"id":"libro-dormir-tapa-dura","nombre":"Libro de cuentos para dormir tapa dura","estado":"Comprado","categoria":"Libros","prioridad":"Alta","precio":"$$","edad":"2-5 años","icono":"🌙","descripcion":"Libro de cuentos para la rutina de sueño.","caracteristicas":["Tapa dura","Historias cortas para dormir","Ilustraciones grandes","Texto simple","Formato resistente"],"busqueda":"libro cuentos dormir tapa dura infantil","linkCompra":"","imagen":"assets/img/productos/librodormir.png"},
  {"id":"gorra-uv","nombre":"Gorra con protección UV","estado":"Comprado","categoria":"Playa y verano","prioridad":"Alta","precio":"$$","edad":"2-4 años","icono":"🧢","descripcion":"Gorra o sombrero para proteger cara y cabeza en días de sol.","caracteristicas":["Protección UV preferentemente UPF 50+","Ala amplia o tipo legionaria","Buen ajuste, que no se vuele","Tela fresca y lavable","Color claro o combinable"],"busqueda":"gorra protección UV niña","linkCompra":"","imagen":"assets/img/productos/gorrouv.png"},
//  {"id":"gorra-visera-canchera-lisa","nombre":"Gorra con visera canchera","estado":"Disponible","categoria":"Ropa y accesorios","prioridad":"Media","precio":"$$","edad":"2-4 años","icono":"🧢","descripcion":"Gorra con visera para uso diario, salidas y fotos.","caracteristicas":["No necesariamente UV","Diseño lindo/canchero","Lisa sin estampa","Buen ajuste","Tela cómoda","Talle infantil 2-4 años","Rosa Claro o Neutro"],"busqueda":"gorra visera niña 2 años canchera","linkCompra":"","imagen":"assets/img/productos/ropa-y-accesorios.svg"}, 
//  {"id":"botella-termica","nombre":"Botella térmica infantil antigoteo","estado":"Disponible","categoria":"Jardín y uso diario","prioridad":"Alta","precio":"$$","edad":"2+ años","icono":"🍼","descripcion":"Botella térmica o vaso infantil para jardín, plaza y viajes.","caracteristicas":["Sistema antigoteo","Tapa segura","Fácil de limpiar","Capacidad aproximada 350-500 ml","Idealmente con sorbete o pico cómodo"],"busqueda":"botella térmica infantil antigoteo","linkCompra":"","imagen":"assets/img/productos/jard-n-y-uso-diario.svg"},
//  {"id":"encastre-colores","nombre":"Juego de encastre y clasificación por colores","estado":"Disponible","categoria":"Montessori y motricidad","prioridad":"Alta","precio":"$$","edad":"2-4 años","icono":"🔴","descripcion":"Juego para clasificar por color, forma o tamaño.","caracteristicas":["Piezas grandes","Sin piezas pequeñas peligrosas","Colores y formas claras","Material madera o plástico resistente","Apto 2+ años"],"busqueda":"juego encastre clasificación colores montessori","linkCompra":"","imagen":"assets/img/productos/montessori-y-motricidad.svg"},
//  {"id":"montessori","nombre":"Material Montessori para motricidad fina","estado":"Disponible","categoria":"Montessori y motricidad","prioridad":"Media","precio":"$$","edad":"2-4 años","icono":"🪵","descripcion":"Tablero de cerraduras, ensartado, broches o actividades de vida práctica.","caracteristicas":["Orientado a motricidad fina","Piezas seguras y grandes","Material resistente","Apto 2-4 años","Evitar piezas muy pequeñas"],"busqueda":"material montessori motricidad fina 2 años","linkCompra":"","imagen":"assets/img/productos/montessori-y-motricidad.svg"},
//  {"id":"libro-solapas","nombre":"Libro interactivo con solapas","estado":"Disponible","categoria":"Libros","prioridad":"Alta","precio":"$","edad":"2-4 años","icono":"📚","descripcion":"Libro con solapas, ventanas o texturas para lectura compartida.","caracteristicas":["Tapa y hojas resistentes","Solapas o texturas","Texto breve","Ilustraciones grandes","Apto 2-4 años"],"busqueda":"libro infantil solapas 2 años","linkCompra":"","imagen":"assets/img/productos/libros.svg"},
//  {"id":"libro-cuentos-grande","nombre":"Libro de cuentos tapa dura grande","estado":"Disponible","categoria":"Libros","prioridad":"Alta","precio":"$$","edad":"2-5 años","icono":"📚","descripcion":"Libro grande, resistente y visual, ideal para leer en familia.","caracteristicas":["Tapa dura","Formato grande","Muchas imágenes","Texto breve o cuentos cortos","Ilustraciones atractivas"],"busqueda":"libro cuentos infantiles tapa dura grande muchas imagenes","linkCompra":"","imagen":"assets/img/productos/libros.svg"},
//  {"id":"temperas","nombre":"Set de témperas lavables, pinceles y hojas grandes","estado":"Disponible","categoria":"Arte y creatividad","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"🎨","descripcion":"Material artístico lavable para pintar libremente.","caracteristicas":["Témperas lavables/no tóxicas","Pinceles gruesos","Hojas grandes","Colores variados","Apto uso infantil supervisado"],"busqueda":"témperas lavables infantiles pinceles hojas","linkCompra":"","imagen":"assets/img/productos/arte-y-creatividad.svg"},
//  {"id":"plastilina","nombre":"Plastilina ultrasuave para niños pequeños","estado":"Disponible","categoria":"Arte y creatividad","prioridad":"Media","precio":"$","edad":"2+ años","icono":"🟣","descripcion":"Plastilina blanda para modelar y juego sensorial supervisado.","caracteristicas":["Ultrasuave","No tóxica","Colores variados","Apta para niños pequeños","Evitar accesorios con piezas chicas"],"busqueda":"plastilina ultrasuave niños pequeños","linkCompra":"","imagen":"assets/img/productos/arte-y-creatividad.svg"},
//  {"id":"bingo-ilustrado","nombre":"Bingo ilustrado","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Baja","precio":"$","edad":"3+ años","icono":"🎲","descripcion":"Bingo con imágenes grandes para jugar en familia.","caracteristicas":["Imágenes claras","Cartones resistentes","Pocas reglas","Apto 3+ años","Ideal animales/objetos cotidianos"],"busqueda":"bingo ilustrado infantil","linkCompra":"","imagen":"assets/img/productos/juegos-did-cticos.svg"},
   ];
