const WHATSAPP_NUMBER = "5491164137699";
const MERCADO_LIBRE_BASE = "https://listado.mercadolibre.com.ar/";

// Para editar la lista:
// - estado: "Disponible", "Reservado" o "Comprado"
// - prioridad: "Alta", "Media" o "Baja"
// - linkCompra: podés reemplazarlo por una URL específica de Mercado Libre o tienda.
// - imagen: podés usar una URL externa o una ruta local dentro de assets/img/productos/.
window.GIFTS = [
  {"id":"uniforme-pantalon","nombre":"Pantalón del uniforme del jardín","estado":"Disponible","categoria":"Ropa y jardín","prioridad":"Alta","precio":"$$","edad":"2-3 años","icono":"👖","descripcion":"Pantalón del uniforme del jardín San Pedro TALLE 1.","caracteristicas":["Talle: 1","Se vende en Carrousel","Álvarez Jonte 4724, C1407"],"busqueda":"pantalón uniforme jardín niña","linkCompra":"https://www.instagram.com/p/DUS-ZUcDoHD/?igsh=c2NpeHhkeXV6Mmo5","imagen":"assets/img/productos/pantalon_san_pedro.jpg"},
  {"id":"remera-blanca-ml","nombre":"Remera manga larga blanca","estado":"Comprado","categoria":"Ropa y jardín","prioridad":"Alta","precio":"$","edad":"2-3 años","icono":"👕","descripcion":"Remera blanca manga larga para jardín y uso diario.","caracteristicas":["Manga larga","Color blanco liso","Algodón o tela suave","Cuello cómodo","Talle a confirmar"],"busqueda":"remera manga larga blanca niña 2 años","linkCompra":"","imagen":"assets/img/productos/remera.png"},
  {"id": "babiators", "nombre": "Lentes de sol Babiators",   "estado": "Disponible",   "categoria": "Playa y verano",   "prioridad": "Alta",  "precio": "$$$", "edad": "3-5 años","icono": "🕶️",  "descripcion": "Lentes de sol infantiles Babiators en color Sweet Cream, ideales para playa, pileta y días de mucho sol.","caracteristicas": [    "Marca preferida: Babiators",    "Color: Sweet Cream",    "Talle recomendado: 3-5Y",    "Protección UV400",    "100% protección UVA/UVB",    "Montura flexible",    "Lentes resistentes a impacto"  ],  "busqueda": "Babiators Sweet Cream 3-5Y",  "linkCompra": "https://tiendamia.com.uy/p/amz/b0dtrfc1ql",  "imagen": "assets/img/productos/lentes.jpg"},
  {"id":"gorra-uv","nombre":"Gorra con protección UV","estado":"Comprado","categoria":"Playa y verano","prioridad":"Alta","precio":"$$","edad":"2-4 años","icono":"🧢","descripcion":"Gorra o sombrero para proteger cara y cabeza en días de sol.","caracteristicas":["Protección UV preferentemente UPF 50+","Ala amplia o tipo legionaria","Buen ajuste, que no se vuele","Tela fresca y lavable","Color claro o combinable"],"busqueda":"gorra protección UV niña 2 años","linkCompra":"","imagen":"assets/img/productos/playa-y-verano.svg"},
  {"id":"gorra-visera-canchera","nombre":"Gorra con visera canchera","estado":"Disponible","categoria":"Ropa y accesorios","prioridad":"Media","precio":"$$","edad":"2-4 años","icono":"🧢","descripcion":"Gorra con visera para uso diario, salidas y fotos.","caracteristicas":["No necesariamente UV","Diseño lindo/canchero","Buen ajuste","Tela cómoda","Talle infantil 2-4 años"],"busqueda":"gorra visera niña 2 años canchera","linkCompra":"","imagen":"assets/img/productos/ropa-y-accesorios.svg"},
  {"id":"malla-uv","nombre":"Malla enteriza con protección UV","estado":"Reservado","categoria":"Playa y verano","prioridad":"Alta","precio":"$$","edad":"2-3 años","icono":"🩱","descripcion":"Malla o traje de baño enterizo para pileta y vacaciones en la playa.","caracteristicas":["Tela con protección UV preferentemente UPF 50+","Enteriza o con buena cobertura","Cómoda para moverse","Secado rápido","Talle 2-3 años a confirmar"],"busqueda":"malla enteriza protección UV niña 2 años","linkCompra":"","imagen":"assets/img/productos/playa-y-verano.svg"},
  {"id":"poncho-playa-uv","nombre":"Poncho de salida de playa UV","estado":"Reservado","categoria":"Playa y verano","prioridad":"Alta","precio":"$$","edad":"2-4 años","icono":"🏖️","descripcion":"Poncho/toallón para salida de mar o pileta.","caracteristicas":["Preferentemente con protección UV o tela de secado rápido","Con capucha","Tamaño infantil","Tela suave","Fácil de lavar"],"busqueda":"poncho salida de playa uv niña 2 años","linkCompra":"","imagen":"assets/img/productos/playa-y-verano.svg"},
  {"id":"calzado-playa","nombre":"Calzado para playa","estado":"Disponible","categoria":"Playa y verano","prioridad":"Media","precio":"$$","edad":"2-3 años","icono":"🩴","descripcion":"Escarpines, sandalias cerradas o calzado acuático para arena, pileta y piedras.","caracteristicas":["Suela antideslizante","Apto agua","Que no se salga fácil","Liviano","Talle a confirmar"],"busqueda":"escarpines sandalias playa niña 2 años","linkCompra":"","imagen":"assets/img/productos/playa-y-verano.svg"},
  {"id":"botella-termica","nombre":"Botella térmica infantil antigoteo","estado":"Disponible","categoria":"Jardín y uso diario","prioridad":"Alta","precio":"$$","edad":"2+ años","icono":"🍼","descripcion":"Botella térmica o vaso infantil para jardín, plaza y viajes.","caracteristicas":["Sistema antigoteo","Tapa segura","Fácil de limpiar","Capacidad aproximada 350-500 ml","Idealmente con sorbete o pico cómodo"],"busqueda":"botella térmica infantil antigoteo","linkCompra":"","imagen":"assets/img/productos/jard-n-y-uso-diario.svg"},
  {"id":"rompecabezas","nombre":"Rompecabezas de 24-48 piezas","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Alta","precio":"$","edad":"2-4 años","icono":"🧩","descripcion":"Rompecabezas progresivo con piezas grandes para atención y motricidad fina.","caracteristicas":["24 a 48 piezas","Piezas grandes y resistentes","Imágenes simples y atractivas","Apto edad 2-4 años","Mejor si es progresivo"],"busqueda":"rompecabezas 24 piezas infantil 3 años","linkCompra":"","imagen":"assets/img/productos/juegos-did-cticos.svg"},
  {"id":"bloques-magneticos","nombre":"Bloques magnéticos","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Alta","precio":"$$$","edad":"3+ años","icono":"🔷","descripcion":"Bloques tipo Magna-Tiles, Connetix o equivalentes para construcción libre.","caracteristicas":["Tipo Magna-Tiles, Connetix o equivalente","Piezas grandes","Imanes encapsulados y seguros","Colores translúcidos","Apto 3+ años"],"busqueda":"bloques magnéticos infantil tipo magna tiles","linkCompra":"","imagen":"assets/img/productos/juegos-did-cticos.svg"},
  {"id":"duplo","nombre":"Bloques de construcción grandes","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Alta","precio":"$$$","edad":"2+ años","icono":"🧱","descripcion":"Tipo LEGO Duplo o similar, con piezas grandes y seguras.","caracteristicas":["Piezas grandes","Compatible tipo Duplo o similar","Apto 2+ años","Fácil de encastrar","Caja básica o temática"],"busqueda":"bloques construcción grandes tipo duplo 2 años","linkCompra":"","imagen":"assets/img/productos/juegos-did-cticos.svg"},
  {"id":"encastre-colores","nombre":"Juego de encastre y clasificación por colores","estado":"Disponible","categoria":"Montessori y motricidad","prioridad":"Alta","precio":"$$","edad":"2-4 años","icono":"🔴","descripcion":"Juego para clasificar por color, forma o tamaño.","caracteristicas":["Piezas grandes","Sin piezas pequeñas peligrosas","Colores y formas claras","Material madera o plástico resistente","Apto 2+ años"],"busqueda":"juego encastre clasificación colores montessori","linkCompra":"","imagen":"assets/img/productos/montessori-y-motricidad.svg"},
  {"id":"montessori","nombre":"Material Montessori para motricidad fina","estado":"Disponible","categoria":"Montessori y motricidad","prioridad":"Media","precio":"$$","edad":"2-4 años","icono":"🪵","descripcion":"Tablero de cerraduras, ensartado, broches o actividades de vida práctica.","caracteristicas":["Orientado a motricidad fina","Piezas seguras y grandes","Material resistente","Apto 2-4 años","Evitar piezas muy pequeñas"],"busqueda":"material montessori motricidad fina 2 años","linkCompra":"","imagen":"assets/img/productos/montessori-y-motricidad.svg"},
  {"id":"memotest","nombre":"Memotest infantil con animales","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Media","precio":"$","edad":"2-4 años","icono":"🐾","descripcion":"Juego de memoria con imágenes simples para vocabulario y concentración.","caracteristicas":["Imágenes de animales","Tarjetas resistentes","Pocas parejas para empezar","Apto 2-4 años","Ilustraciones claras"],"busqueda":"memotest animales infantil","linkCompra":"","imagen":"assets/img/productos/juegos-did-cticos.svg"},
  {"id":"libro-solapas","nombre":"Libro interactivo con solapas","estado":"Disponible","categoria":"Libros","prioridad":"Alta","precio":"$","edad":"2-4 años","icono":"📚","descripcion":"Libro con solapas, ventanas o texturas para lectura compartida.","caracteristicas":["Tapa y hojas resistentes","Solapas o texturas","Texto breve","Ilustraciones grandes","Apto 2-4 años"],"busqueda":"libro infantil solapas 2 años","linkCompra":"","imagen":"assets/img/productos/libros.svg"},
  {"id":"libro-dormir-tapa-dura","nombre":"Libro de cuentos para dormir tapa dura","estado":"Reservado","categoria":"Libros","prioridad":"Alta","precio":"$$","edad":"2-5 años","icono":"🌙","descripcion":"Libro de cuentos para la rutina de sueño.","caracteristicas":["Tapa dura","Historias cortas para dormir","Ilustraciones grandes","Texto simple","Formato resistente"],"busqueda":"libro cuentos dormir tapa dura infantil","linkCompra":"","imagen":"assets/img/productos/libros.svg"},
  {"id":"libro-cuentos-grande","nombre":"Libro de cuentos tapa dura grande","estado":"Disponible","categoria":"Libros","prioridad":"Alta","precio":"$$","edad":"2-5 años","icono":"📚","descripcion":"Libro grande, resistente y visual, ideal para leer en familia.","caracteristicas":["Tapa dura","Formato grande","Muchas imágenes","Texto breve o cuentos cortos","Ilustraciones atractivas"],"busqueda":"libro cuentos infantiles tapa dura grande muchas imagenes","linkCompra":"","imagen":"assets/img/productos/libros.svg"},
  {"id":"temperas","nombre":"Set de témperas lavables, pinceles y hojas grandes","estado":"Disponible","categoria":"Arte y creatividad","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"🎨","descripcion":"Material artístico lavable para pintar libremente.","caracteristicas":["Témperas lavables/no tóxicas","Pinceles gruesos","Hojas grandes","Colores variados","Apto uso infantil supervisado"],"busqueda":"témperas lavables infantiles pinceles hojas","linkCompra":"","imagen":"assets/img/productos/arte-y-creatividad.svg"},
  {"id":"plastilina","nombre":"Plastilina ultrasuave para niños pequeños","estado":"Disponible","categoria":"Arte y creatividad","prioridad":"Media","precio":"$","edad":"2+ años","icono":"🟣","descripcion":"Plastilina blanda para modelar y juego sensorial supervisado.","caracteristicas":["Ultrasuave","No tóxica","Colores variados","Apta para niños pequeños","Evitar accesorios con piezas chicas"],"busqueda":"plastilina ultrasuave niños pequeños","linkCompra":"","imagen":"assets/img/productos/arte-y-creatividad.svg"},
  {"id":"balance-bike","nombre":"Bicicleta de equilibrio","estado":"Disponible","categoria":"Aire libre","prioridad":"Alta","precio":"$$$","edad":"2-5 años","icono":"🚲","descripcion":"Balance bike sin pedales para equilibrio y coordinación.","caracteristicas":["Sin pedales","Asiento regulable","Liviana","Ruedas resistentes","Apta desde 2 años"],"busqueda":"bicicleta equilibrio niña 2 años balance bike","linkCompra":"","imagen":"assets/img/productos/aire-libre.svg"},
  {"id":"pelota-futbol","nombre":"Pelota de fútbol N.º 3","estado":"Disponible","categoria":"Aire libre","prioridad":"Media","precio":"$","edad":"2+ años","icono":"⚽","descripcion":"Pelota liviana tamaño infantil para plaza, patio o playa.","caracteristicas":["Tamaño N.º 3","Liviana","Material blando o bajo peso","Apta para niños","Diseño resistente"],"busqueda":"pelota fútbol número 3 infantil","linkCompra":"","imagen":"assets/img/productos/aire-libre.svg"},
  {"id":"cocina","nombre":"Cocina de juguete","estado":"Disponible","categoria":"Juego simbólico","prioridad":"Alta","precio":"$$$","edad":"2-5 años","icono":"🍳","descripcion":"Cocina infantil para juego simbólico e imitación.","caracteristicas":["Estructura estable","Apta 2+ años","Accesorios grandes","Sin piezas peligrosas","Tamaño infantil"],"busqueda":"cocina juguete infantil madera plastico","linkCompra":"","imagen":"assets/img/productos/juego-simb-lico.svg"},
  {"id":"banco-herramientas","nombre":"Banco de herramientas","estado":"Disponible","categoria":"Juego simbólico","prioridad":"Alta","precio":"$$$","edad":"2-5 años","icono":"🛠️","descripcion":"Banco o set de herramientas infantiles para juego simbólico.","caracteristicas":["Herramientas grandes y seguras","Apto 2+ años","Estructura estable","Sin piezas pequeñas peligrosas","Material resistente"],"busqueda":"banco herramientas infantil juguete 2 años","linkCompra":"","imagen":"assets/img/productos/juego-simb-lico.svg"},
  {"id":"torre-aprendizaje","nombre":"Torre de aprendizaje","estado":"Disponible","categoria":"Montessori y motricidad","prioridad":"Alta","precio":"$$$","edad":"18m+","icono":"🪜","descripcion":"Learning Tower para participar en cocina o lavarse manos con supervisión.","caracteristicas":["Muy estable","Barandas de seguridad","Altura adecuada","Terminaciones redondeadas","Madera resistente"],"busqueda":"torre aprendizaje montessori infantil","linkCompra":"","imagen":"assets/img/productos/montessori-y-motricidad.svg"},
  {"id":"mesa-silla","nombre":"Juego de mesa y sillas infantil","estado":"Comprado","categoria":"Muebles infantiles","prioridad":"Media","precio":"$$$","edad":"2-6 años","icono":"🪑","descripcion":"Set bajo para dibujar, leer, comer o jugar.","caracteristicas":["Mesa baja + silla/s","Esquinas redondeadas","Fácil limpieza","Estructura estable","Tamaño infantil"],"busqueda":"mesa silla infantil madera","linkCompra":"","imagen":"assets/img/productos/mesa.png"},
  {"id":"biblioteca-frontal","nombre":"Biblioteca frontal Montessori","estado":"Disponible","categoria":"Muebles infantiles","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"📖","descripcion":"Biblioteca baja con libros a la vista para favorecer autonomía.","caracteristicas":["Frontal, libros visibles","Altura baja","Estructura estable","Sin puntas filosas","Madera o material resistente"],"busqueda":"biblioteca frontal montessori infantil","linkCompra":"","imagen":"assets/img/productos/muebles-infantiles.svg"},
  {"id":"carpa-tipi","nombre":"Carpa tipi","estado":"Disponible","categoria":"Juego simbólico","prioridad":"Media","precio":"$$$","edad":"2+ años","icono":"⛺","descripcion":"Espacio de juego, lectura o descanso.","caracteristicas":["Estructura estable","Tela lavable","Tamaño apto interior","Fácil de armar","Sin piezas peligrosas"],"busqueda":"carpa tipi infantil","linkCompra":"","imagen":"assets/img/productos/juego-simb-lico.svg"},
  {"id":"tunel","nombre":"Túnel plegable","estado":"Disponible","categoria":"Aire libre","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"🌀","descripcion":"Túnel para gatear, esconderse y moverse.","caracteristicas":["Plegable","Tela resistente","Apto interior/exterior","Sin varillas expuestas","Tamaño infantil"],"busqueda":"túnel plegable infantil","linkCompra":"","imagen":"assets/img/productos/aire-libre.svg"},
  {"id":"pizarra","nombre":"Pizarra magnética","estado":"Disponible","categoria":"Arte y creatividad","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"✏️","descripcion":"Pizarra para dibujar, pegar imanes y practicar trazos.","caracteristicas":["Magnética","Lavable","Liviana o estable","Apta niños","Mejor si incluye marcadores/imanes grandes"],"busqueda":"pizarra magnética infantil","linkCompra":"","imagen":"assets/img/productos/arte-y-creatividad.svg"},
  {"id":"caballete","nombre":"Caballete doble","estado":"Disponible","categoria":"Arte y creatividad","prioridad":"Media","precio":"$$$","edad":"2+ años","icono":"🖍️","descripcion":"Caballete con pizarra, tiza o rollo de papel.","caracteristicas":["Doble faz preferentemente","Altura infantil","Estructura estable","Fácil limpieza","Compatible con papel o pizarra"],"busqueda":"caballete doble infantil pizarra","linkCompra":"","imagen":"assets/img/productos/arte-y-creatividad.svg"},
  {"id":"domino-animales","nombre":"Dominó de animales","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Baja","precio":"$","edad":"2-4 años","icono":"🦁","descripcion":"Dominó simple con ilustraciones de animales.","caracteristicas":["Ilustraciones grandes","Piezas resistentes","Animales reconocibles","Reglas simples","Apto 2-4 años"],"busqueda":"dominó animales infantil","linkCompra":"","imagen":"assets/img/productos/juegos-did-cticos.svg"},
  {"id":"bingo-ilustrado","nombre":"Bingo ilustrado","estado":"Disponible","categoria":"Juegos didácticos","prioridad":"Baja","precio":"$","edad":"3+ años","icono":"🎲","descripcion":"Bingo con imágenes grandes para jugar en familia.","caracteristicas":["Imágenes claras","Cartones resistentes","Pocas reglas","Apto 3+ años","Ideal animales/objetos cotidianos"],"busqueda":"bingo ilustrado infantil","linkCompra":"","imagen":"assets/img/productos/juegos-did-cticos.svg"},
  {"id":"disfraz","nombre":"Disfraz","estado":"Disponible","categoria":"Juego simbólico","prioridad":"Media","precio":"$$","edad":"2-4 años","icono":"🩺","descripcion":"Disfraz de médica, veterinaria, cocinera u otro rol.","caracteristicas":["Talle 2-4 años","Tela cómoda","Fácil de poner y sacar","Accesorios seguros","Preferencia: médica, veterinaria o cocinera"],"busqueda":"disfraz infantil médica veterinaria cocinera","linkCompra":"","imagen":"assets/img/productos/juego-simb-lico.svg"},
  {"id":"jardineria","nombre":"Kit de jardinería infantil","estado":"Disponible","categoria":"Exploración","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"🌱","descripcion":"Palita, rastrillo, regadera y guantes pequeños.","caracteristicas":["Herramientas de tamaño infantil","Bordes seguros","Regadera liviana","Material resistente","Ideal para patio o macetas"],"busqueda":"kit jardinería infantil","linkCompra":"","imagen":"assets/img/productos/exploraci-n.svg"},
  {"id":"toy-story-buddy","nombre":"Muñeco Toy Story Woody","estado":"Comprado","categoria":"Personajes y muñecos","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"🤠","descripcion":"Muñeco de personaje Toy Story para juego simbólico.","caracteristicas":["Personaje: Woody según disponibilidad","Tamaño infantil","Material resistente","Sin piezas pequeñas peligrosas","Apto para 2+ años"],"busqueda":"muñeco toy story buddy woody","linkCompra":"","imagen":"assets/img/productos/woody.png"},
  {"id":"toy-story-jessie","nombre":"Muñeco Toy Story Jessie","estado":"Comprado","categoria":"Personajes y muñecos","prioridad":"Media","precio":"$$","edad":"2+ años","icono":"👢","descripcion":"Muñeca Jessie de Toy Story para juego simbólico.","caracteristicas":["Personaje: Jessie","Tamaño infantil","Material resistente","Sin piezas pequeñas peligrosas","Apto para 2+ años"],"busqueda":"muñeco toy story jessie","linkCompra":"","imagen":"assets/img/productos/jessie.png"}
];
